# Generated by Django 4.2.6 on 2024-02-20 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_course_student'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='person',
            managers=[
            ],
        ),
    ]
