# Generated by Django 4.2.6 on 2024-03-06 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_image'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='image',
            managers=[
            ],
        ),
    ]
